### ISSUE TITLE
Not an issue, Just a note

### ISSUE THREAD

**Issue by Viswas-Programs** [hsanger/survivreloaded#16]
I found the assets of surviv.io in google drive linked by kongregate in their forum's old post. Link to that is here -> https://drive.google.com/drive/folders/1qhaDdNCsisBu_7gvMNmyn_zkG4kyAZix

And also, the existing method to get assets, well, you get it from the surviv.io server, but that server is shutdown isn't it?
And wouldn't this get copyrighted by Kong, because this is publicly hosted in survivreloaded.com, so if Kong comes accross that website, couldn't they make a copyright claim?

**Comment by hsanger** [comment]
Yep, I know about the Creator Kit.

Kong definitely could make a copyright claim. We're just hoping they don't notice or care about this project. If they do make a copyright claim, the only way for the project to continue would be to make a new client entirely from scratch.

**Comment by Viswas-Programs** [comment]
And, wouldn't that take ALOT Of time?
What I suggest is to start build a new client right away, because, you don't know if kong is going to come here, and stop a good game development, because they want surviv.io out of existence.
