### ISSUE TITLE
Whenever I run index.html, it brings up really gibberish

### ISSUE THREAD

**Issue by Viswas-Programs** [hsanger/survivreloaded#21]
After starting my server up with npm start, then, I opened `survivreloaded\public\index.html" file and then, it shows a bare bone HTML page!
Look at this for a reference
![image](https://user-images.githubusercontent.com/115633223/223910581-0f2f5d4c-d9cc-4c57-80dd-e65737a1c16b.png)
And also, HARDCODED PATHS !?!?!?look at line 1 in the error console, it says "C:\app<gibberish>" not found!

**Comment by lopste** [comment]
You don’t start it up using local files, you go to local host on whatever
port it’s hosted on.

**Comment by Viswas-Programs** [comment]
Ohhh ok, I did the way of open surviv. Io method

**Comment by Viswas-Programs** [comment]
UPDATE on this issue: As the guy said, I hosted the local host server, and, when I try to go to 127.0.0.1:8000, I get that same broken html page.
Here is a reference for screenshot
![image](https://user-images.githubusercontent.com/115633223/223957746-47db42f4-22e9-4ceb-81b0-50bf42a6686a.png)

**Comment by hsanger** [comment]
Something's wrong with your copy of the client. To download a complete copy of the client, click here: https://wormhole.app/jbK1q#fixctvqMv_eb8zjUB97oRQ

**Comment by Viswas-Programs** [comment]
> Something's wrong with your copy of the client. To download a complete copy of the client, click here: https://wormhole.app/jbK1q#fixctvqMv_eb8zjUB97oRQ 

I git cloned this repo from the command line, is that wrong?

**Comment by hsanger** [comment]
No, that’s correct. You cloned the server from the repo. The client needs to be downloaded separately.

**Comment by hsanger** [comment]
Extract the zip file I sent you. Put the ‘public’ folder you extracted in the repo folder.

**Comment by Viswas-Programs** [comment]
Even after extracting and putting into the repo main folder, it still shows gibberish
And, I even tried rebuilding the npm modules...

**Comment by Viswas-Programs** [comment]
My repo folder structure looks like this.
![image](https://user-images.githubusercontent.com/115633223/224039175-cec64546-ef67-4196-af3e-c878b310218a.png)

**Comment by hsanger** [comment]
Looks like you extracted the files directly in the repo folder. The client files should be in the `public` folder.

**Comment by Viswas-Programs** [comment]
so along with the server files? let me try that...

**Comment by Viswas-Programs** [comment]
So update, now it works man, thank you
Now, I have 2 working attempts of surviv resurrection projects


CRINGE NOTE: 
I have the best of both worlds here, I have opensurviv.io as well as this survivreloaded.com all cloned into my computer!

**Comment by Viswas-Programs** [comment]
Update::
I browsed into the folder when I saw this...
![image](https://user-images.githubusercontent.com/115633223/224243939-c56918ae-5b86-4544-87ff-12a691f6c358.png)

What does that folder do, I mean data dumps mean memory crash dumps? like my browser generated some kind of memory dump onto those json files?
Can you explain what is that dump folder?
